# Generated by Django 6.0.4 on 2026-05-19 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontlook', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_user_role_id', models.CharField(max_length=50)),
                ('tasker_toto_id', models.CharField(max_length=50)),
                ('tasker_phone', models.CharField(max_length=15)),
                ('collected_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('given_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_record', to='frontlook.booking')),
            ],
        ),
    ]
