# Generated by Django 6.0.4 on 2026-05-19 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontlook', '0002_booking'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_user_role_id', models.CharField(max_length=50, verbose_name='Service User Role ID')),
                ('tasker_toto_id', models.CharField(max_length=50, verbose_name='Tasker Totoo ID')),
                ('money_amount_sent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Sent by User')),
                ('money_amount_given', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Amount Given to Tasker (80%)')),
                ('platform_retained', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Totoo Platform Cut (20%)')),
                ('user_transaction_id', models.CharField(max_length=100, unique=True, verbose_name='User TrxID')),
                ('tasker_transaction_id', models.CharField(max_length=100, unique=True, verbose_name='Tasker TrxID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail', to='frontlook.booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments_info',
            },
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
