# Generated by Django 6.0.4 on 2026-04-30 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskerprofile',
            old_name='experience_years',
            new_name='experience',
        ),
        migrations.RemoveField(
            model_name='taskerprofile',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='taskerprofile',
            name='certification',
        ),
        migrations.AlterField(
            model_name='taskerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tasker_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
