# Generated by Django 6.0.4 on 2026-04-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_rename_experience_years_taskerprofile_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskerprofile',
            old_name='experience',
            new_name='experience_years',
        ),
        migrations.AddField(
            model_name='taskerprofile',
            name='certification',
            field=models.FileField(blank=True, null=True, upload_to='certs/'),
        ),
    ]
