# Generated by Django 6.0.4 on 2026-04-30 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_rename_experience_taskerprofile_experience_years_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskerprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='taskerprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='taskerprofile',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='taskerprofile',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='taskerprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskerprofile',
            name='giving_services',
            field=models.TextField(blank=True, help_text='Describe the services you offer'),
        ),
        migrations.AddField(
            model_name='taskerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='taskerprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='worker_profiles/'),
        ),
        migrations.AddField(
            model_name='taskerprofile',
            name='work_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='worker_portfolio/'),
        ),
        migrations.AddField(
            model_name='taskerprofile',
            name='work_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='worker_portfolio/'),
        ),
        migrations.AddField(
            model_name='taskerprofile',
            name='work_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='worker_portfolio/'),
        ),
        migrations.AlterField(
            model_name='taskerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tasker_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
