# Generated by Django 6.0.4 on 2026-04-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_remove_taskerprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskerprofile',
            name='giving_services',
        ),
        migrations.RemoveField(
            model_name='taskerprofile',
            name='work_image_1',
        ),
        migrations.RemoveField(
            model_name='taskerprofile',
            name='work_image_2',
        ),
        migrations.RemoveField(
            model_name='taskerprofile',
            name='work_image_3',
        ),
        migrations.AddField(
            model_name='taskerprofile',
            name='category',
            field=models.CharField(blank=True, help_text='e.g., Plumber, Electrician, Designer', max_length=100),
        ),
        migrations.AddField(
            model_name='taskerprofile',
            name='payment_receive_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='taskerprofile',
            name='service_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskerprofile',
            name='totooid',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
