# Generated by Django 6.0.4 on 2026-05-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_remove_taskerprofile_giving_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskerprofile',
            name='info_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='worker_docs/'),
        ),
        migrations.AddField(
            model_name='taskerprofile',
            name='info_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='worker_docs/'),
        ),
        migrations.AddField(
            model_name='taskerprofile',
            name='info_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='worker_docs/'),
        ),
    ]
