# Generated by Django 6.0.4 on 2026-05-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_taskerprofile_info_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskerprofile',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Starting price for your service (Money Demand)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='taskerprofile',
            name='service_info',
            field=models.TextField(blank=True, help_text='Work Bio / Service Description'),
        ),
    ]
