# Generated by Django 6.0.4 on 2026-04-28 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toto_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profiles/pics/')),
                ('address', models.TextField(blank=True)),
                ('work_info', models.TextField(blank=True)),
                ('info_image_1', models.ImageField(blank=True, upload_to='profiles/verify/')),
                ('info_image_2', models.ImageField(blank=True, upload_to='profiles/verify/')),
                ('info_image_3', models.ImageField(blank=True, upload_to='profiles/verify/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
