# Generated by Django 6.0.4 on 2026-04-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuserprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
