# Generated by Django 6.0.4 on 2026-04-29 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceuser', '0002_serviceuserprofile_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceuserprofile',
            name='info_image_1',
        ),
        migrations.RemoveField(
            model_name='serviceuserprofile',
            name='info_image_2',
        ),
        migrations.RemoveField(
            model_name='serviceuserprofile',
            name='info_image_3',
        ),
        migrations.RemoveField(
            model_name='serviceuserprofile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='serviceuserprofile',
            name='work_info',
        ),
        migrations.AlterField(
            model_name='serviceuserprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('access_level', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_link', models.URLField(blank=True)),
                ('specialization', models.CharField(blank=True, help_text='Frontend/Backend', max_length=100, null=True)),
                ('is_active_dev', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
