# Generated by Django 6.0.4 on 2026-05-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceuser', '0003_remove_serviceuserprofile_info_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuserprofile',
            name='info_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='service_docs/'),
        ),
        migrations.AddField(
            model_name='serviceuserprofile',
            name='info_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='service_docs/'),
        ),
        migrations.AddField(
            model_name='serviceuserprofile',
            name='info_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='service_docs/'),
        ),
        migrations.AddField(
            model_name='serviceuserprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='service_users/'),
        ),
        migrations.AddField(
            model_name='serviceuserprofile',
            name='work_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
